export type UserRole = 'Admin' | 'Broker';

export type AppView = 
  | 'dashboard' 
  | 'properties' 
  | 'clients' 
  | 'sales' 
  | 'leasing' 
  | 'ads'
  | 'spreadsheets' 
  | 'reminders' 
  | 'activities' 
  | 'marketing' 
  | 'tasks' 
  | 'brokers' 
  | 'network' 
  | 'lead_import' 
  | 'backup' 
  | 'restore' 
  | 'documents' 
  | 'construction_companies' 
  | 'cash_flow' 
  | 'launches'
  | 'client_payment_flow'
  | 'monthly_financial'
  | 'password_update';

export const ALL_PERMISSIONS: AppView[] = [
  'dashboard', 'tasks', 'properties', 'clients', 'marketing', 'sales', 
  'leasing', 'ads', 'spreadsheets', 'activities', 'reminders', 'brokers', 
  'network', 'lead_import', 'backup', 'restore', 'documents', 
  'construction_companies', 'cash_flow', 'launches', 'client_payment_flow',
  'monthly_financial',
  'password_update'
];

export enum ClientStatus {
  LEAD = 'Lead',
  COLD = 'Frio',
  WARM = 'Morno',
  HOT = 'Quente',
  WON = 'Ganho'
}

export const PropertyStatus = {
  AVAILABLE: 'Disponível',
  RESERVED: 'Reservado',
  SOLD: 'Vendido',
  RENTED: 'Alugado',
  LAUNCH: 'Lançamento'
} as const;

export interface Property {
  id: string;
  brokerId: string;
  brokerName: string;
  code: string; 
  title: string;
  projectName?: string; 
  constructionCompany?: string; 
  type: string; 
  listingType?: string; 
  transactionType: 'Venda' | 'Locação' | 'Ambos';
  description: string; 
  address: string;
  neighborhood: string;
  referencePoint?: string;
  price: number; 
  rentPrice?: number; 
  bedrooms: number;
  bathrooms: number;
  area: number;
  status: string; 
  imageUrl: string;
  gallery?: string[];
  watermarkText?: string;
  watermarkImage?: string; 
  watermarkOpacity?: number; 
  applyWatermark?: boolean;
  coordinates: { lat: number; lng: number };
  acceptsExchange: boolean;
  ownerName: string;
  ownerPhone: string;
  updatedAt: string;
}

export interface RentalContract {
  id: string;
  propertyId: string;
  propertyTitle: string;
  clientId: string;
  clientName: string;
  startDate: string;
  endDate: string;
  monthlyValue: number;
  status: 'Active' | 'Expired' | 'Pending_Payment' | 'Terminated';
  guarantorName?: string;
  updatedAt: string;
}

export interface LaunchProject {
  id: string;
  name: string;
  builder: string;
  city: string;
  deliveryDate: string;
  progress: number;
  status: 'Pre-Launch' | 'Under-Construction' | 'Finished';
  unitsAvailable: number;
  imageUrl?: string;
  description?: string;
  allocatedClientIds: string[];
  updatedAt: string;
}

export interface VettusDocument {
  id: string;
  brokerId: string;
  brokerName: string;
  name: string;
  category: 'Contrato' | 'Identidade' | 'Escritura' | 'Financeiro' | 'Outros';
  size: string;
  type: string;
  data: string; // Base64
  date: string;
}

export interface Broker {
  id: string;
  name: string;
  email: string;
  password?: string;
  pendingPassword?: string;
  role: UserRole;
  avatar?: string;
  joinDate: string;
  performance: number;
  permissions?: AppView[]; 
  lastSync?: string;
  networkId?: string;
  blocked?: boolean;
  deleted?: boolean;
  updatedAt?: string;
}

export interface Client {
  id: string;
  brokerId: string;
  name: string;
  email: string;
  phone: string;
  status: ClientStatus;
  lastContact: string;
  budget: number;
  assignedAgent: string;
  preference?: string;
  desiredPropertyType?: string;
  nextActivityDate?: string;
  nextActivityTime?: string;
  nextActivityType?: 'Call' | 'Meeting' | 'Viewing' | 'Email' | 'WhatsApp' | 'Call_Back';
  spouseName?: string;
  spousePhone?: string;
  blocked?: boolean;
  blockReason?: string;
  updatedAt: string;
}

export interface Activity {
  id: string;
  brokerId: string;
  brokerName?: string;
  type: 'Call' | 'Meeting' | 'Viewing' | 'Email' | 'WhatsApp' | 'System';
  clientName: string;
  description: string;
  date: string;
  time: string;
  updatedAt: string;
}

export interface SystemActivity {
  id: string;
  brokerId: string;
  brokerName: string;
  action: string;
  target: string;
  updatedAt: string;
}

export interface Reminder {
  id: string;
  brokerId: string;
  title: string;
  dueDate: string;
  priority: 'High' | 'Medium' | 'Low';
  completed: boolean;
  autoGenerated?: boolean;
  type?: 'standard' | 'overdue' | 'transfer' | 'new_lead';
  metadata?: string;
  updatedAt: string;
}

export interface PaymentItem {
  date: string;
  value: number;
}

export interface PaymentProposal {
  signalValue: number;
  signalMethod: string;
  downPaymentValue: number;
  downPaymentDate: string;
  monthlyInstallments: PaymentItem[];
  balloons: PaymentItem[];
  postConstructionValue?: number;
}

export interface Commission {
  id: string;
  brokerId: string;
  propertyTitle: string;
  propertyCode?: string;
  unitNumber?: string;
  blockOrTower?: string;
  salePrice?: number; 
  amount: number;
  brokerAmount: number;
  agencyAmount: number;
  status: 'Pending' | 'Paid';
  date: string;
  expectedPaymentDate?: string;
  clientName: string;
  proposalDetails?: string;
  structuredProposal?: PaymentProposal;
  updatedAt: string;
}

export type SalesStage = 'Lead' | 'Frio' | 'Morno' | 'Quente' | 'Ganho';

export interface Task {
  id: string;
  brokerId: string;
  title: string;
  clientName: string;
  agent: string;
  dueDate: string;
  stage: SalesStage;
  priority: 'High' | 'Medium' | 'Low';
  value: number;
  updatedAt: string;
}

export interface Campaign {
  id: string;
  brokerId: string;
  name: string;
  status: 'Draft' | 'Active' | 'Completed';
  sentCount: number;
  openRate: number;
  segment: string;
  updatedAt: string;
}

export interface ConstructionCompany {
  id: string;
  name: string;
  commissionRate: number;
  releaseFluxRate: number;
  closingDay: number;
  brokerPercent: number;
  agencyPercent: number;
  updatedAt: string;
}

export interface CommissionForecast {
  id: string;
  clientId: string;
  clientName: string;
  constructionCompanyId: string;
  constructionCompanyName: string;
  saleId: string;
  salePrice: number;
  paidPercent: number;
  commissionAmount: number;
  forecastDate: string;
  status: 'Pendente' | 'Recebido' | 'Aguardando Fluxo';
  updatedAt: string;
}

export interface Expense {
  id: string;
  brokerId: string;
  description: string;
  value: number;
  category: string;
  dueDate: string;
  paymentDate?: string;
  status: 'Pendente' | 'Pago';
  payer?: 'Fluxo de Caixa' | 'Sócio: Sergio' | 'Sócio: Leonardo';
  month: number; // 1-12
  year: number;
  updatedAt: string;
}
